### ISSUE TITLE
Some comments in /etc/pacman.conf aren't ignored

### ISSUE THREAD

**Issue by faho** [Kwpolska/pkgbuilder#38]
I have `ILoveCandy #Pacman style progress bar` as a standalone line in my pacman.conf, and `pkgbuilder -Du` fails with 

>(|) Initializing pacman access.../usr/lib/python3.4/site-packages/pycman/config.py:132: InvalidSyntax: unable to parse /etc/pacman.conf, unrecognized option: 'ILoveCandy #Pacman style progress bar'
  warnings.warn(InvalidSyntax(f.name, 'unrecognized option', key))

Adding a space after the "#" doesn't help, but removing the comment does.

**Comment by Kwpolska** [comment]
I’m really sorry, but I can’t help. This is handled by pycman, not something I control.

@remyoudompheng, would you mind looking into this?
