### ISSUE TITLE
pb ignores -p/--print-format for aur

### ISSUE THREAD

**Issue by FirefighterBlu3** [Kwpolska/pkgbuilder#40]
```log
[david@Scott ~]$ pb -S --print-format '%r/%n-%v' grep
core/grep-2.23-1

[david@Scott ~]$ pb -S --print-format '%r/%n-%v' pkgbuilder
==> Building pkgbuilder...
  -> aur/pkgbuilder 4.2.4-2 (25 votes) [installed]
  ->     A Python AUR helper/library.
==> Cloning the git repository...
^C==> ERROR: Aborted by user! Exiting...
```

shouldn't it print out `aur/pkgbuilder-4.2.4-2`?

**Comment by Kwpolska** [comment]
I might implement that one day. Please keep in mind that `pb` is only a thin wrapper — in case a feature is not supported by PKGBUILDer or pacman, it will only work for certain packages.

**Comment by Kwpolska** [comment]
I don’t think this will be a useful feature. I’ll close this, but if anyone really needs it, they could send a PR.
