### ISSUE TITLE
Allow parallell compressing

### ISSUE THREAD

**Issue by Dr-Horv** [Kwpolska/pkgbuilder#42]
Seems compression is done with _xz_. Would it be possible to switch to some parallell method such as [_pxz_](https://aur.archlinux.org/packages/pxz/) to speed up installations?

**Comment by Kwpolska** [comment]
I think you should ask the `makepkg` developers about this. PKGBUILDer is just running `makepkg` to do the compression. You may also try changing the settings in `makepkg.conf` (`COMPRESSXZ` option)

**Comment by Dr-Horv** [comment]
Ah yes after som digging I realized this. Thanks for the quick response.

**Comment by Kwpolska** [comment]
Closing, because this can’t be solved by me/globally.
