### ISSUE TITLE
Support unicode char in packages descriptions

### ISSUE THREAD

**Issue by tchabaud** [Kwpolska/pkgbuilder#43]
Hello,

Since I've installed [letsencrypt-git](https://aur.archlinux.org/packages/letsencrypt-git) package, I've the following error displayed each time I try to update with command *pkgbuilder -Syu* : 

```
:: Synchronizing package databases...
--- Logging error ---            
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pkgbuilder/package.py", line 113, in from_aurdict
    setattr(p, bindings[k], v)
KeyError: 'Keywords'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 259: ordinal not in range(128)
Call stack:
  File "/usr/bin/pkgbuilder", line 9, in <module>
    load_entry_point('pkgbuilder==4.2.6', 'console_scripts', 'pkgbuilder')()
  File "/usr/lib/python3.5/site-packages/pkgbuilder/__main__.py", line 299, in main
    dodowngrade, DS.vcsupgrade, DS.fetch)
  File "/usr/lib/python3.5/site-packages/pkgbuilder/upgrade.py", line 112, in auto_upgrade
    gradable = list_upgradable(foreign.keys(), vcsup)
  File "/usr/lib/python3.5/site-packages/pkgbuilder/upgrade.py", line 48, in list_upgradable
    aurlist = pkgbuilder.utils.info(pkglist)
  File "/usr/lib/python3.5/site-packages/pkgbuilder/utils.py", line 41, in info
    return [AURPackage.from_aurdict(d) for d in aur_pkgs['results']]
  File "/usr/lib/python3.5/site-packages/pkgbuilder/utils.py", line 41, in <listcomp>
    return [AURPackage.from_aurdict(d) for d in aur_pkgs['results']]
  File "/usr/lib/python3.5/site-packages/pkgbuilder/package.py", line 117, in from_aurdict
    k, aurdict)
Message: 'AURDict has an unknown %s key: %s'
Arguments: ('Keywords', {'LastModified': 1457041506, 'Description': 'A tool to automatically receive and install X.509 certificates to enable TLS on servers. The client will interoperate with the Let\u2019s Encrypt CA which will be issuing browser-trusted certificates for free.', 'Keywords': ['apache', 'certificate', 'encryption', 'git', 'nginx', 'security', 'web'], 'PackageBaseID': 95253, 'Version': '5704.f2390ed-1', 'URL': 'https://letsencrypt.org/', 'NumVotes': 21, 'Conflicts': ['letsencrypt', 'letsencrypt-nginx', 'letsencrypt-apache', 'letshelp-letsencrypt'], 'FirstSubmitted': 1435352772, 'Name': 'letsencrypt-git', 'License': ['Apache'], 'Provides': ['letsencrypt', 'letsencrypt-nginx', 'letsencrypt-apache', 'letshelp-letsencrypt'], 'Maintainer': 'edh', 'ID': 281158, 'URLPath': '/cgit/aur.git/snapshot/letsencrypt-git.tar.gz', 'Popularity': 2.227569, 'PackageBase': 'letsencrypt-git', 'OutOfDate': None, 'Depends': ['python2', 'augeas', 'ca-certificates', 'dialog', 'openssl', 'gcc', 'libffi', 'git', 'python-virtualenv', 'pkg-config']})
```

I think it's related to unicode character in this package description.

Can you fix it please ? I'm sorry I can't help, but I don't know python enough.

**Comment by Kwpolska** [comment]
1. How is your `locale` configured? Are you using UTF-8 locales everywhere?
2. PKGBUILDer version?

**Comment by tchabaud** [comment]
Here's my *locale* output : 

```sh
> locale
LANG=fr_FR.utf8
LC_CTYPE="fr_FR.utf8"
LC_NUMERIC="fr_FR.utf8"
LC_TIME="fr_FR.utf8"
LC_COLLATE=C
LC_MONETARY="fr_FR.utf8"
LC_MESSAGES="fr_FR.utf8"
LC_PAPER="fr_FR.utf8"
LC_NAME="fr_FR.utf8"
LC_ADDRESS="fr_FR.utf8"
LC_TELEPHONE="fr_FR.utf8"
LC_MEASUREMENT="fr_FR.utf8"
LC_IDENTIFICATION="fr_FR.utf8"
LC_ALL=
```

I'm using *pkgbuilder* version 4.2.6 : 

```sh
> pkgbuilder -V
PKGBUILDer v4.2.6
```

**Comment by tchabaud** [comment]
Sorry, I just realized I've clicked the wrong button :confounded:

**Comment by Kwpolska** [comment]
This bug is caused by me not noticing a new variable in the AUR JSON (I’ll fix that in the next version, which should be up in a few minutes) and by a locale error. Are you sure this `fr_FR.utf8` locale is listed by `locale -a`? If yes, can you reproduce with `LC_CTYPE='fr_FR.utf8' pkgbuilder -Syu`?

**Comment by tchabaud** [comment]
```sh
> locale -a
C
POSIX
en_US
en_US.iso88591
en_US.utf8
fr_FR
fr_FR.iso88591
fr_FR.iso885915@euro
fr_FR.utf8
fr_FR@euro
french
```

Then update : 

̀```sh
> env LC_CTYPE='fr_FR.utf8' pkgbuilder -Syu
:: Synchronizing package databases...
:: Starting full system upgrade...

Targets (1):

Name        Old Version  New Version

pkgbuilder  4.2.6-1      4.2.7-1    

:: Proceed with installation? [Y/n] y
==> Building pkgbuilder...
  -> aur/pkgbuilder 4.2.7-1 (26 votes) [installed: 4.2.6-1]
  ->     A Python AUR helper/library.
==> Cloning the git repository...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 2), reused 0 (delta 0)
Dépaquetage des objets: 100% (4/4), fait.
Depuis https://aur.archlinux.org/pkgbuilder
   31b4bd2..0adae49  master     -> origin/master
Mise à jour 31b4bd2..0adae49
Fast-forward
 .SRCINFO | 6 +++---
 PKGBUILD | 4 ++--
 2 files changed, 5 insertions(+), 5 deletions(-)
==> Checking dependencies...
  -> python-requests: found in system
  -> git: found in system
  -> python-srcinfo: found in system
  -> python-setuptools: found in system
  -> python: found in system
  -> pyalpm: found in system
  -> rsync: found in system
==> Création du paquet pkgbuilder 4.2.7-1 (mer. mars 23 20:35:48 CET 2016)
==> Vérification des dépendances pour l’exécution...
==> Vérification des dépendances pour la compilation...
==> Récupération des sources...
  -> Téléchargement de pkgbuilder-4.2.7.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 82721  100 82721    0     0  40914      0  0:00:02  0:00:02 --:--:-- 40930
==> Validation des fichiers source avec md5sums...
    pkgbuilder-4.2.7.tar.gz ... Réussite
==> Extraction des sources...
  -> Extraction de pkgbuilder-4.2.7.tar.gz avec bsdtar
==> Suppression du répertoire $pkgdir/ existant...
==> Entre dans l’environnement fakeroot...
==> Lancement de package()...
[...]
Installing pkgbuilder script to /tmp/pkgbuilder-1000/pkgbuilder/pkg/pkgbuilder/usr/bin
==> Nettoyage de l’installation...
  -> Suppression des répertoires vides... 
  -> Suppression des fichiers libtool...
  -> Suppression des fichiers indésirables...
  -> Suppression des fichiers de bibliothèques statiques...
  -> Nettoyage des symboles inutiles dans les fichiers binaires et les bibliothèques...
  -> Compression des pages de man/info...
==> Recherche des erreurs d’empaquetage…
==> Création du paquet « pkgbuilder »...
  -> Génération du fichier .PKGINFO...
  -> Génération du fichier .BUILDINFO...
  -> Génération du fichier .MTREE...
  -> Compression du paquet... 
==> Quitte l’environnement fakeroot.
==> Création finie : pkgbuilder 4.2.7-1 (mer. mars 23 20:35:53 CET 2016)
==> The build succeeded.
==> Installing built packages...
==> Running transaction from file /tmp/pkgbuilder-1000/pkgbuilder-1458761753.tx...
  -> Moving to /var/cache/pacman/pkg/...
  -> Installing with pacman -U...
chargement des paquets...
résolution des dépendances...
recherche des conflits entre paquets...

Paquets (1) pkgbuilder-4.2.7-1

Taille totale installée :     0,36 MiB
Taille de mise à jour nette :  0,00 MiB

:: Procéder à l’installation ? [O/n] o
(1/1) vérification des clés dans le trousseau                                                  [########################################################] 100%
(1/1) vérification de l’intégrité des paquets                                                  [########################################################] 100%
(1/1) chargement des fichiers des paquets                                                      [########################################################] 100%
(1/1) analyse des conflits entre fichiers                                                      [########################################################] 100%
(1/1) vérification de l’espace disque disponible                                               [########################################################] 100%
:: Traitement des changements du paquet...
(1/1) mise à jour de pkgbuilder                                                                [########################################################] 100%
==> Validating installation status...
  -> pkgbuilder: installed 4.2.7-1
==> Transaction succeeded.
  -> Deleted transaction file /tmp/pkgbuilder-1000/pkgbuilder-1458761753.tx
```
and without forcing locale : 

```
> pkgbuilder -Syu
:: Synchronizing package databases...
:: Starting full system upgrade...
 there is nothing to do
```

Thanks a lot for the quick fix, and for pkgbuilder. It's a great tool !

**Comment by Kwpolska** [comment]
You’re welcome!

On a side note, PKGBUILDer could use some translations: https://www.transifex.com/kwpolska/pkgbuilder — mind providing some for French?

**Comment by tchabaud** [comment]
I'll be glad to help. Can you authorize me to join team please ?

**Comment by Kwpolska** [comment]
I added you (tchabaud) to the French team. Happy translating!
