### ISSUE TITLE
change dir

### ISSUE THREAD

**Issue by atommixz** [Kwpolska/pkgbuilder#45]
Can i change in config directory for building? Can I change directory for source?

**Comment by Kwpolska** [comment]
On Wed, Apr 06, 2016 at 03:12:45PM -0700, atommixz wrote:
> Can i change in config directory for building? Can I change directory for source?
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Kwpolska/pkgbuilder/issues/45

What directories? By default, PB uses either the current working directory (default) or /tmp/pkgbuilder-UID/ (-S). I could make it a config setting, but that would need some other changes.

Also, note that storing sources and build data in different places is unlikely to be supported.

-- 
Chris Warrick <https://chriswarrick.com/>
PGP: 5EAAEA16

**Comment by atommixz** [comment]
I have /tmp with 128MB in tmpfs on my VPS and it not enough for me. And current working directory it joke. I do not want to change the directory each time and follow this. It required wrapper where current dir will be changed to clearly set.
So it's very strange behavior, useless for me. It's not alternative for yaourt.

**Comment by Kwpolska** [comment]
You could’ve just asked nicely… I could implement that as a special config option. I probably will soon.
