### ISSUE TITLE
--ignore and IgnorePkg are not supported

### ISSUE THREAD

**Issue by hepha** [Kwpolska/pkgbuilder#46]
if updates can't --ignore  chromium-dev 

 grep chromium-dev /etc/pacman.conf 

IgnorePkg   =  linux-uksm-ck linux-uksm-ck-headers chromium-dev linux-ck linux-ck-headers libutvideo-git  firefox-kde-opensuse firefox firefox-kde qmmp-svn clang-svn 

pb --ignore chromium-dev  -Su

Targets (8):

Name                                 Old Version              New Version            

chromium-dev                         50.0.2661.18-1           51.0.2700.0-1          
dropbox                              3.16.1-1                 3.18.1-1               
plasma5-applets-thermal-monitor-git  r52.617e1ff-1            r56.c22f2b6-1          
ttf-font-awesome                     4.5.0-2                  4.6.1-1                
uchardet                             0.0.5-1                  0.0.5-2                
vivaldi                              1.0.435.40-1             1.0.435.42-1           
you-get-git                          0.4.365.20160406.1222-1  0.4.365.20160413.1226-1
zpaq                                 7.10-1                   7.11-1

th

**Comment by Kwpolska** [comment]
We currently ignore unsupported options in `pb`. I’ll work on implementing this.

**Comment by hepha** [comment]
Thank you, I understan

**Comment by Kwpolska** [comment]
`--ignore` now supported. `IgnorePkg` won’t, because in principle, PKGBUILDer ignores pacman config.
