### ISSUE TITLE
4.2.8.r3.g73398b9 have bug

### ISSUE THREAD

**Issue by hepha** [Kwpolska/pkgbuilder#47]
hello 
4.2.8.r3.g73398b9 have bug

> Traceback (most recent call last):
>   File "/usr/bin/pb", line 9, in <module>
>     load_entry_point('pkgbuilder==4.2.8', 'console_scripts', 'pb')()
>   File "/usr/lib/python3.5/site-packages/pkgbuilder/wrapper.py", line 34, in main
>     pkgbuilder.wrapper.wrapper()
>   File "/usr/lib/python3.5/site-packages/pkgbuilder/wrapper.py", line 296, in wrapper
>     pbmain(pbargs + pbpkgnames)
>   File "/usr/lib/python3.5/site-packages/pkgbuilder/__main__.py", line 333, in main
>     DS.pkginst, pkgnames)
>   File "/usr/lib/python3.5/site-packages/pkgbuilder/build.py", line 52, in auto_build
>     build_result = build_runner(pkgname, performdepcheck, pkginstall)
>   File "/usr/lib/python3.5/site-packages/pkgbuilder/build.py", line 433, in build_runner
>     prefixp='  -> ')
>   File "/usr/lib/python3.5/site-packages/pkgbuilder/utils.py", line 78, in print_package_search
>     termwidth = get_termwidth(9001)
>   File "/usr/lib/python3.5/site-packages/pkgbuilder/ui.py", line 30, in get_termwidth
>     return shutil.get_terminal_size((default, default)).columns
> NameError: name 'shutil' is not defined

**Comment by Kwpolska** [comment]
On Tue, Apr 19, 2016 at 01:36:32AM -0700, hepha wrote:
> hello 
> 4.2.8.r3.g73398b9 have bug
> 
> > Traceback (most recent call last):
> >   File "/usr/bin/pb", line 9, in <module>
> >     load_entry_point('pkgbuilder==4.2.8', 'console_scripts', 'pb')()
> >   File "/usr/lib/python3.5/site-packages/pkgbuilder/wrapper.py", line 34, in main
> >     pkgbuilder.wrapper.wrapper()
> >   File "/usr/lib/python3.5/site-packages/pkgbuilder/wrapper.py", line 296, in wrapper
> >     pbmain(pbargs + pbpkgnames)
> >   File "/usr/lib/python3.5/site-packages/pkgbuilder/__main__.py", line 333, in main
> >     DS.pkginst, pkgnames)
> >   File "/usr/lib/python3.5/site-packages/pkgbuilder/build.py", line 52, in auto_build
> >     build_result = build_runner(pkgname, performdepcheck, pkginstall)
> >   File "/usr/lib/python3.5/site-packages/pkgbuilder/build.py", line 433, in build_runner
> >     prefixp='  -> ')
> >   File "/usr/lib/python3.5/site-packages/pkgbuilder/utils.py", line 78, in print_package_search
> >     termwidth = get_termwidth(9001)
> >   File "/usr/lib/python3.5/site-packages/pkgbuilder/ui.py", line 30, in get_termwidth
> >     return shutil.get_terminal_size((default, default)).columns
> > NameError: name 'shutil' is not defined
> 
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Kwpolska/pkgbuilder/issues/47

Thanks for reporting this bug! I forgot an import statement. Should be fixed now — please update your `pkgbuilder-git` package manually.

-- 
Chris Warrick <https://chriswarrick.com/>
PGP: 5EAAEA16
