### ISSUE TITLE
can't use pb install ABS packages

### ISSUE THREAD

**Issue by hepha** [Kwpolska/pkgbuilder#48]
Please fix, thank you

`pb plasma-workspace`
Error : There is no specified operation ( use -h for help )

   `pkgbuilder plasma-workspace`
==> Building plasma-workspace... 
  -> extra/plasma-workspace 5.6.3-1 [installed]
  ->     KDE Plasma Workspace
==> Retrieving from ABS...
receiving file list ... done
extra/plasma-workspace/PKGBUILD
extra/plasma-workspace/kde.pam

sent 160 bytes  received 243 bytes  89.56 bytes/sec
total size is 3,254  speedup is 8.07
==> Checking dependencies...
Traceback (most recent call last):
  File "/usr/bin/pkgbuilder", line 9, in <module>
    load_entry_point('pkgbuilder==4.2.8', 'console_scripts', 'pkgbuilder')()
  File "/usr/lib/python3.5/site-packages/pkgbuilder/__main__.py", line 339, in main
    DS.pkginst, pkgnames)
  File "/usr/lib/python3.5/site-packages/pkgbuilder/build.py", line 52, in auto_build
    build_result = build_runner(pkgname, performdepcheck, pkginstall)
  File "/usr/lib/python3.5/site-packages/pkgbuilder/build.py", line 476, in build_runner
    depends = prepare_deps(os.path.abspath('./.SRCINFO'))
  File "/usr/lib/python3.5/site-packages/pkgbuilder/build.py", line 201, in prepare_deps
    with open(srcinfo_path, encoding='utf-8') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hepha/extra/plasma-workspace/.SRCINFO'

**Comment by Kwpolska** [comment]
I forgot about this part, sorry. I’ll try to fix it, probably by requiring `mksrcinfo` (as I don’t want to re-introduce my bashy parser)

**Comment by Kwpolska** [comment]
`pkgbuilder plasma-workspace` will work now. `pb` does not support ABS builds — you can only install a binary package (`pb -S plasma-workspace`)
