### ISSUE TITLE
pkgbuilder fails to install arduino from AUR

### ISSUE THREAD

**Issue by timlag1305** [Kwpolska/pkgbuilder#49]
`pkgbuilder` fails to install `arduino 1:1.6.12-1`:

    $ pkgbuilder arduino
    ==> Building arduino...
      -> aur/arduino 1:1.6.12-1 (515 votes)
      ->     Arduino prototyping platform SDK
    ==> Cloning the git repository...
    Cloning into 'arduino'...
    remote: Counting objects: 6, done.
    remote: Compressing objects: 100% (6/6), done.
    remote: Total 6 (delta 0), reused 0 (delta 0)
    Unpacking objects: 100% (6/6), done.
    ==> Checking dependencies...
    ==> ERROR: Failed to fulfill package dependency requirement: java-runtime=8 (Package: arduino-1:1.6.12-1)

I do in fact have the java-runtime installed:

    $ java --version
    openjdk version "1.8.0_102"
    OpenJDK Runtime Environment (build 1.8.0_102-b14)
    OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

**Comment by Kwpolska** [comment]
What Java-related packages have you got installed? Can you install the `arduino` package manually?

```
pkgbuilder -F arduino
cd arduino
makepkg -si
```

**Comment by timlag1305** [comment]
That actually worked.  I initially had the openjdk 8 installed from the arch repositories.

**Comment by Kwpolska** [comment]
I’ll look into why it fails on Saturday.

**Comment by Kwpolska** [comment]
This happens because the `arduino` package specifies its version requirements for java as `=8` which cannot be met (but somehow, makepkg/pacman doesn’t care). I’m not sure what to do here, perhaps try asking the maintainer of that package to set a different set of version requirements (greater than 8, less than 9)?

**Comment by timlag1305** [comment]
Okay, thanks.  I'll bring this up with the package maintainer.
