### ISSUE TITLE
Fix RPC requests pls

### ISSUE THREAD

**Issue by SolarAquarion** [Kwpolska/pkgbuilder#53]
It seems doing one request on about 500 packages at once will make this project fail.  To fix it, would be too split up the RPC calls into a more manageable amount

**Comment by Kwpolska** [comment]
How does it fail? What errors do you get?

**Comment by SolarAquarion** [comment]
solaraquarion@apollo   ~  pkgbuilder -Syu             ✓  2511  08:01:32 
:: Synchronizing package databases...
==> ERROR: Network error: HTTP Error 414 (via <Response [414]>) (via <Response [414]>)
==> ERROR: PKGBUILDer (or the requests library) had problems with fulfilling an HTTP request.

><sheep> SolarAquarion: your AUR helper is probably trying to query for way too many packages at once
><sheep> it should split up the requests

**Comment by Kwpolska** [comment]
I think I fixed it. Could you please test if it works? Replace `/usr/lib/python3.6/site-packages/pkgbuilder/aur.py` with [the updated version](https://raw.githubusercontent.com/Kwpolska/pkgbuilder/c0824e8e51b6e8f6187a06b208bb2c060bddef3e/pkgbuilder/aur.py) and tell me if that works.

**Comment by SolarAquarion** [comment]
@Kwpolska it works beautifully
