### ISSUE TITLE
gpg invalid signature

### ISSUE THREAD

**Issue by L0ric0** [Kwpolska/pkgbuilder#58]
after yesterdays update ther is a problem with the gpg signiture for the repo:
```
error: pkgbuilder: signature from "Chris Warrick <kwpolska@gmail.com>" is unknown trust
error: failed to update pkgbuilder (invalid or corrupted database (PGP signature))
```

**Comment by Kwpolska** [comment]
My GPG key expires every year. Run this:

    # pacman-key -d 5EAAEA16
    # pacman-key -r 5EAAEA16
    # pacman-key --lsign 5EAAEA16
    # pacman -Syyu
