### ISSUE TITLE
[4.3.2-3] ModuleNotFoundError: No module named 'pycman'

### ISSUE THREAD

**Issue by jeremywh7** [Kwpolska/pkgbuilder#72]
I haven't run pkgbuilder in a few weeks, but today it is failing with the following output (even just running '--help'):
![image](https://github.com/Kwpolska/pkgbuilder/assets/3794434/669f5517-27df-467d-83fb-55f9e72da07c)

**Comment by Kwpolska** [comment]
Please try upgrading to Python 3.12 and the latest version (4.3.2-4).

**Comment by jeremywh7** [comment]
It's working, after I removed 'asp' from the dependencies as trying to install it gave a key error, even after importing the key.  Looks like it should be removed from PKGBUILD...?

**Comment by Kwpolska** [comment]
The `asp` package seems to exist on the AUR: https://aur.archlinux.org/packages/asp

**Comment by jeremywh7** [comment]
That's where I was trying to install it from; it fails due to the key error, even after importing said key (and cleaning the directory, just in case).
